DATASET:
  BATCH_SIZE: 5
  NAME: 'Baxter'
OUTPUT:
  LOG_ITER: 100
  EVAL_ITER: 1000
  MAX_ITER: 10000
  SAVE_ITER: 1000
  BASE_DIR: "../weights"
OPTIM:
  LR: 1e-4
  SCHEDULER:
    GAMMA: 0.99
    STEP: 1000
VAE:
  LATENT_DIM: 32
  KLD_WEIGHT: 0.01